[build]
    command = "npm i " # Your build command
    functions = "functions" # The directory with your serverless functions
    publish = "./" # The directory with your built site

[dev]
    command = "npm start" # The command to start your development server
    functions = "functions" # The directory with your serverless functions
    publish = "./" # The directory with your built site
